[package]
name = "hw1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
log = "0.4.20"
regex = "1.9.5"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
